services:
  movies-nestjs:
    container_name: movies-nestjs
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
    - .env
    command: yarn dev
    ports:
      - 8080:8080
    depends_on:
      - redis
      - postgres
  redis: # Name of container
    image: redis
    container_name: redis-movies-nestjs
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  postgres:
    image: postgres
    container_name: database-movies-nestjs
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data
volumes:
  redis:
    driver: local
  docker-nest-postgres:
    driver: local
